// Rebuilds the rows in src/frontend/data.js from the backend's seeds (every file in src/backend/db/seeds, in name order),
// keeping the table of fixes. Run from anywhere: node src/frontend/tools/seed-to-data.js
const fs = require('fs'), path = require('path');
const root = path.resolve(__dirname, '../../..');
const seedDir = path.join(root, 'src/backend/db/seeds');
const dataPath = path.join(root, 'src/frontend/data.js');
const old = fs.readFileSync(dataPath, 'utf8');

// one SQL value list: numbers, 'strings' ('' is a quote), NULL, TRUE, FALSE; commas inside strings are kept
function values(s) {
  const out = []; let i = 0;
  while (i < s.length) {
    while (s[i] === ' ' || s[i] === ',') i++;
    if (i >= s.length) break;
    if (s[i] === "'") {
      let t = ''; i++;
      while (i < s.length) { if (s[i] === "'" && s[i + 1] === "'") { t += "'"; i += 2; } else if (s[i] === "'") { i++; break; } else t += s[i++]; }
      out.push(t);
    } else {
      const j = s.indexOf(',', i), w = s.slice(i, j < 0 ? s.length : j).trim(); i = j < 0 ? s.length : j;
      out.push(w === 'NULL' ? null : w === 'TRUE' ? true : w === 'FALSE' ? false : Number(w));
    }
  }
  return out;
}

// every INSERT INTO methane_incidents in every seed, in order: ids follow insert order, as in a fresh database
const rows = [];
for (const file of fs.readdirSync(seedDir).filter(f => f.endsWith('.sql')).sort()) {
  const sql = fs.readFileSync(path.join(seedDir, file), 'utf8');
  for (const ins of sql.matchAll(/INSERT INTO methane_incidents \(([^)]*)\)\s*VALUES([\s\S]*?);/g)) {
    const cols = ins[1].split(',').map(c => c.trim());
    for (const m of ins[2].matchAll(/^\s*\((.*?)\)\s*,?\s*(?:--\s*(.*))?$/gm)) {   // lazy: a comment after the tuple may hold brackets too
      const v = values(m[1]);
      if (v.length !== cols.length) throw new Error(`${file}: ${v.length} values for ${cols.length} columns in: ${m[1].slice(0, 80)}`);
      rows.push({ row: { id: rows.length + 1, ...Object.fromEntries(cols.map((c, k) => [c, v[k]])) }, place: (m[2] || '').trim() });
    }
  }
}
if (!rows.length) throw new Error('no rows found in the seeds');

const kb = old.slice(old.indexOf('  // Indicative fixes'), old.indexOf('\n\n  window.MRS_DATA'));
if (!kb.includes('const interventions')) throw new Error('table of fixes not found in data.js');

const lit = o => '{ ' + Object.entries(o).filter(([, v]) => v !== null).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join(', ') + ' }';
fs.writeFileSync(dataPath, `/* Offline copy of the database: the backend's seeds (src/backend/db/seeds), in the shape GET /incidents returns.
   The page shows these rows when the incident API can't be reached, so offline and live show the same incidents. Ids follow insert order, as in a fresh database.
   Rows with is_real: true are public SRON detections (CC BY 4.0, see the seed file); the others are the synthetic demo seed.
   Generated by tools/seed-to-data.js; rerun it when a seed changes. The table of fixes below is ours: the database has none. */
(() => {
  const rows = [
${rows.map(r => `    ${lit(r.row)},${r.place ? `   // ${r.place}` : ''}`).join('\n')}
  ];

${kb.trimEnd()}

  window.MRS_DATA = { version: 'seed-2', rows, interventions };
})();
`);
console.log(`data.js: ${rows.length} rows from the seeds (${rows.filter(r => r.row.is_real).length} real)`);
